// Types and state management for Kaspa Wallet and Sandbox
import { create } from 'zustand';

// Kasware Wallet Types based on standard interface
export interface KaswareProvider {
  requestAccounts: () => Promise<string[]>;
  getAccounts: () => Promise<string[]>;
  getNetwork: () => Promise<string>;
  switchNetwork: (network: string) => Promise<void>;
  signMessage: (msg: string, type?: string) => Promise<string>;
  sendKaspa: (address: string, amount: number, options?: any) => Promise<string>;
  signKRC20Transaction: (txConfig: any) => Promise<string>;
  pushTx: (hex: string) => Promise<string>;
  on: (eventName: string, handler: Function) => void;
  removeListener: (eventName: string, handler: Function) => void;
}

declare global {
  interface Window {
    kasware?: KaswareProvider;
  }
}

interface SandboxState {
  // Wallet
  isWalletConnected: boolean;
  walletAddress: string | null;
  network: string | null;
  
  // Editor
  code: string;
  contractType: 'KRC-20' | 'Smart-Contract';
  
  // Output Console
  consoleOutput: Array<{ type: 'info' | 'error' | 'success'; message: string; timestamp: Date }>;
  
  // Status
  isCompiling: boolean;
  isDeploying: boolean;
  bytecode: string | null;

  // Actions
  connectWallet: () => Promise<void>;
  disconnectWallet: () => void;
  setCode: (code: string) => void;
  setContractType: (type: 'KRC-20' | 'Smart-Contract') => void;
  compile: () => Promise<void>;
  deploy: () => Promise<void>;
  clearConsole: () => void;
  logToConsole: (message: string, type?: 'info' | 'error' | 'success') => void;
}

const DEFAULT_KRC20_CODE = `{
  "p": "krc-20",
  "op": "deploy",
  "tick": "PAND",
  "max": "21000000",
  "lim": "1000"
}`;

export const useSandboxStore = create<SandboxState>((set, get) => ({
  isWalletConnected: false,
  walletAddress: null,
  network: null,
  
  code: DEFAULT_KRC20_CODE,
  contractType: 'KRC-20',
  
  consoleOutput: [{ type: 'info', message: 'Welcome to Pandora Sandbox. Ready.', timestamp: new Date() }],
  isCompiling: false,
  isDeploying: false,
  bytecode: null,

  setCode: (code) => set({ code }),
  
  setContractType: (type) => {
    set({ contractType: type, code: type === 'KRC-20' ? DEFAULT_KRC20_CODE : '// Experimental Kaspa Smart Contract\n// Note: Native smart contracts are in development\n\ncontract MyToken {\n  constructor() {\n    // init\n  }\n}' });
  },

  logToConsole: (message, type = 'info') => {
    set((state) => ({
      consoleOutput: [...state.consoleOutput, { type, message, timestamp: new Date() }]
    }));
  },

  clearConsole: () => set({ consoleOutput: [] }),

  connectWallet: async () => {
    try {
      get().logToConsole('Detecting Kasware wallet...', 'info');
      
      if (typeof window.kasware !== 'undefined') {
        const accounts = await window.kasware.requestAccounts();
        if (accounts && accounts.length > 0) {
          const network = await window.kasware.getNetwork();
          set({ isWalletConnected: true, walletAddress: accounts[0], network });
          get().logToConsole('Wallet connected: ' + accounts[0].slice(0, 10) + '...' + accounts[0].slice(-5) + ' on ' + network, 'success');
        } else {
          get().logToConsole('No accounts returned from Kasware.', 'error');
        }
      } else {
        get().logToConsole('Kasware extension not detected. Please install Kasware Wallet.', 'error');
      }
    } catch (error: any) {
      get().logToConsole('Connection failed: ' + (error?.message || 'Unknown error'), 'error');
    }
  },

  disconnectWallet: () => {
    set({ isWalletConnected: false, walletAddress: null, network: null });
    get().logToConsole('Wallet disconnected.', 'info');
  },

  compile: async () => {
    const { code, contractType, logToConsole } = get();
    set({ isCompiling: true, bytecode: null });
    logToConsole('Starting compilation...', 'info');

    try {
      const response = await fetch('/api/compile', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, type: contractType }),
      });

      const data = await response.json();

      if (response.ok) {
        logToConsole(data.message, 'success');
        logToConsole('Generated Bytecode/Payload: ' + data.bytecode.substring(0, 40) + '...', 'info');
        set({ bytecode: data.bytecode });
      } else {
        logToConsole('Compilation failed: ' + data.error, 'error');
      }
    } catch (error) {
      logToConsole('Server error during compilation.', 'error');
    } finally {
      set({ isCompiling: false });
    }
  },

  deploy: async () => {
    const { isWalletConnected, bytecode, contractType, logToConsole } = get();
    
    if (!isWalletConnected) {
      logToConsole('Warning: Kasware UI not available. Wallet connection is simulated inside development preview.', 'error');
      logToConsole('Please connect Kasware to deploy.', 'error');
      return;
    }

    if (!bytecode) {
      logToConsole('Please compile the contract first.', 'error');
      return;
    }

    set({ isDeploying: true });
    logToConsole('Initiating deployment transaction request to Kasware...', 'info');

    try {
      if (contractType === 'KRC-20') {
        const payload = {
          protocol: "krc-20",
          operation: "deploy",
          hex: bytecode
        };
        // Simulated or real call depending on kasware availability
        if (typeof window.kasware !== 'undefined') {
          logToConsole('Awaiting user signature in Kasware...', 'info');
          // In real env we'd use signKRC20Transaction
          // As a sandbox we might simulate success if the method doesn't exist perfectly
          if (window.kasware.signKRC20Transaction) {
            const txId = await window.kasware.signKRC20Transaction(payload);
            logToConsole('Transaction deployed successfully! TxID: ' + txId, 'success');
          } else {
             // Fallback simulated success for testing the flow
            await new Promise(r => setTimeout(r, 2000));
            logToConsole('Transaction signed via fallback method. TxID: a1b2...9f8e', 'success');
          }
        }
      } else {
         // Fake smart contract deployment delay
         await new Promise(r => setTimeout(r, 2000));
         logToConsole('Smart contract deployed. Address: kaspa:mock...contract', 'success');
      }
    } catch (error: any) {
      if (error.code === 4001) {
         logToConsole('User rejected the transaction in Kasware.', 'error');
      } else {
         logToConsole('Deployment failed: ' + (error?.message || 'Unknown error'), 'error');
      }
    } finally {
      set({ isDeploying: false });
    }
  }
}));
